feat(dataclass): Support `frozen=True` in py_class (#54)
This PR brings support for `frozen=True` so that one could create
dataclass instances with immutability. For example,

```python
import mlc.dataclasses as mlcd

@mlcd.py_class(frozen=True)
class Frozen(mlcd.PyClass):
    a: int
    b: str

x = Frozen(a=1, b="b")

>>> x.a = 2  # not allowed to set a field
AttributeError: property 'a' of 'Frozen' object has no setter
```

And if one has to forcefully set attributes, there's a private API:

```python
>>> x._mlc_setattr("a", 3)
>>> x.a
3
```

This design is consistent with python's [native
dataclass](https://docs.python.org/3/library/dataclasses.html#frozen-instances),
where it uses `object.__setattr__` to force-set fields